name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-python:
    name: Test Python Implementation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd gil-py
          pip install -e .[dev]

      - name: Run linting
        run: |
          cd gil-py
          ruff check .

      - name: Run type checking
        run: |
          cd gil-py
          mypy gil/

      - name: Run tests
        run: |
          cd gil-py
          pytest --cov=gil --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./gil-py/coverage.xml
          flags: python
          name: python-${{ matrix.python-version }}

  test-website:
    name: Test Next.js Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'gil-flow-site/package-lock.json'

      - name: Install dependencies
        run: |
          cd gil-flow-site
          npm ci

      - name: Run linting
        run: |
          cd gil-flow-site
          npm run lint

      - name: Run build
        run: |
          cd gil-flow-site
          npm run build

  validate-workflows:
    name: Validate Example Workflows
    runs-on: ubuntu-latest
    needs: test-python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install gil-flow
        run: |
          cd gil-py
          pip install -e .

      - name: Validate example workflows
        run: |
          cd gil-py/tests
          for workflow in *.yaml; do
            echo "Validating $workflow"
            gil-flow validate "$workflow"
          done