name: Publish Python packages to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    name: Build and publish Python packages to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for trusted publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build and publish gil-py
        run: |
          python -m build gil-py/
          twine upload gil-py/dist/* --verbose
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

      - name: Build and publish gil-node-openai
        run: |
          python -m build gil-py/nodes/gil-node-openai/
          twine upload gil-py/nodes/gil-node-openai/dist/* --verbose
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

      - name: Build and publish gil-node-text
        run: |
          python -m build gil-py/nodes/gil-node-text/
          twine upload gil-py/nodes/gil-node-text/dist/* --verbose
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

      - name: Build and publish gil-node-data
        run: |
          python -m build gil-py/nodes/gil-node-data/
          twine upload gil-py/nodes/gil-node-data/dist/* --verbose
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}